server:
  port: 9060
# netty配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
# netty配置
netty:
  websocket:
    # Websocket服务端口
    port: 9061
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
    max-frame-size: 10240
    # URI路径
    path: /channel
spring:
  # kafka配置
  kafka:
    bootstrap-servers: 182.92.215.222:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 重试次数
      retries: 3
# kafka系统参数
kafka:
  # 主题名称
  topic-name:
    # 新增告警信息时触发
    create-alarm-info: example-topic-name1
    create-alarm-info2: example-topic-name2




## netty配置
#netty:
#  # boss线程数量 默认为cpu线程数*2
#  boss: 1
#  # worker线程数量 默认为cpu线程数*2
#  worker: 4
#  # 连接超时时间 默认为30s
#  timeout: 6000
#  # 服务器主端口 默认7000
#  port: 7000
#  # 服务器备用端口 默认70001
#  portSalve: 7001
#  # 服务器地址 默认为本地
#  host: 127.0.0.1
#  # tcp参数 1024个队列
#  tcp: 1024